load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "cc_with_plugin",
    srcs = ["cc_with_plugin.bzl"],
)

bzl_library(
    name = "dict",
    srcs = ["dict.bzl"],
)

bzl_library(
    name = "llvm_config_bzl",
    srcs = ["llvm_config.bzl"],
)
